variable "name" {}
variable "project" {}
variable "environment" {}
variable "vpc_cidr_block" {}
variable "private_subnet1_cidr_block" {}
variable "private_subnet2_cidr_block" {}
variable "public_subnet1_cidr_block" {}
variable "public_subnet2_cidr_block" {}
variable "availability_zones" {}
variable "cc_jumpbox_ami" {}
variable "ipa_jumpbox_ami" {}
variable "instance_type" {}
variable "key_name" {}
variable "aws_region" {}
variable "vpc_name" {}
